### ISSUE TITLE
Stale link in OSC docs

### ISSUE THREAD

**Issue by pq** [monome/serialosc#24]
In the arc section:

http://nomeist.com/osc/arc/

is dead. 😢

**Comment by wrl** [comment]
hey, where are you seeing that link? I'm having trouble finding the arc section you're talking about.

**Comment by pq** [comment]
Ah, sorry.  It's here: <http://monome.org/docs/osc/>.

Maybe this an issue more for the `monome` site proper?  Not sure where those pages are hosted actually but maybe they should be a wiki or something living here?

**Comment by tehn** [comment]
fixed
