### ISSUE TITLE
Consider hosting a serialosc FAQ.

### ISSUE THREAD

**Issue by pq** [monome/serialosc#25]
See for example the recent comments on the lines thread [Serial OSC Crash](http://llllllll.co/t/serialosc-crash/1950/17).  It'd be great to assemble a FAQ.  If not here, then maybe a new repo in [monome-community](https://github.com/monome-community) for community supported docs?

/cc @tehn @jasonw22

**Comment by pq** [comment]
FWIW, this exists now and might be a better home for some user docs:

https://github.com/monome-community/monome-docs

**Comment by tehn** [comment]
agreed and will mark this as an issue for the monome docs site.
