### ISSUE TITLE
Use system libuv instead of submodule?

### ISSUE THREAD

**Issue by simonvanderveldt** [monome/serialosc#30]
I'd like to propose to use system installed libuv instead of a git submodule. Would it be OK to switch to this?

I have a patch for `./wscript` that adds the required check. It's working fine for me (Linux/gentoo, libuv 1.10.2) this way. Can create a PR using this code if you're open to this change.

I guess there's no system installed libuv on macos and windows? So for those the submodule should stay in place?

**Comment by wrl** [comment]
"switch" as in leave no way to build with submodule? no, no chance. submodule is necessary for macOS and windows build, yes.

I'm open to a PR which preferentially uses the system libuv and falls back to the submodule if it's unavailable.

**Comment by simonvanderveldt** [comment]
> "switch" as in leave no way to build with submodule? no, no chance. submodule is necessary for macOS and windows build, yes.

OK, I figured as much :)
I'll make sure it only applies to linux

> I'm open to a PR which preferentially uses the system libuv and falls back to the submodule if it's unavailable.

Cool, I'll create a PR to do so.
I'd prefer the configure step to fail if there's no system libuv, would that be OK for you?

**Comment by wrl** [comment]
how about it checks for the submodule first and falls back to the system libuv if it's not found? that way it's easier to override the system version if need be (for example, debugging libuv).

**Comment by simonvanderveldt** [comment]
Yeah, that makes sense. Allows one to easily override if one wants to and can fail if both are missing. I'll do that.
Good idea :)

**Comment by simonvanderveldt** [comment]
This was fixed in #32
