### ISSUE TITLE
no longer builds, macos 10.13

### ISSUE THREAD

**Issue by tehn** [monome/serialosc#39]
i haven't built serialosc for awhile now, but these don't seem to be 10.13 specific issues.

anyone?

../src/common/ipc.c:109:28: error: taking address of packed member 'devnode' of class or structure 'sosc_ipc_msg::(anonymous union)::(anonymous)' may result in an unaligned pointer value [-Werror,-Waddress-of-packed-member]
                if (read_strdata(fd, 1, &buf->connection.devnode))
                                         ^~~~~~~~~~~~~~~~~~~~~~~
../src/common/ipc.c:117:28: error: taking address of packed member 'serial' of class or structure 'sosc_ipc_msg::(anonymous union)::(anonymous)' may result in an unaligned pointer value [-Werror,-Waddress-of-packed-member]
                if (read_strdata(fd, 2, &buf->device_info.serial,
                                         ^~~~~~~~~~~~~~~~~~~~~~~
../src/common/ipc.c:118:21: error: taking address of packed member 'friendly' of class or structure 'sosc_ipc_msg::(anonymous union)::(anonymous)' may result in an unaligned pointer value [-Werror,-Waddress-of-packed-member]
                                 &buf->device_info.friendly))
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~
3 errors generated.

Waf: Leaving directory `/Users/tehn/Work/lib/serialosc/build'
Build failed
 -> task in 'serialosc-common' failed (exit status 1):
	{task 4431184592: c ipc.c -> ipc.c.2.o}
['/usr/bin/clang', '-mmacosx-version-min=10.5', '-std=c99', '-Wall', '-Werror', '-I/Users/tehn/Work/lib/serialosc/build', '-I/Users/tehn/Work/lib/serialosc', '-I/Users/tehn/Work/lib/serialosc/build/include', '-I/Users/tehn/Work/lib/serialosc/include', '-I/Users/tehn/Work/lib/serialosc/build/third-party', '-I/Users/tehn/Work/lib/serialosc/third-party', '-DHAVE_LIBMONOME=1', '-DHAVE_LO=1', '-DHAVE_STRDUP=1', '-DHAVE_STRNDUP=1', '-DHAVE_STRCASECMP=1', '-DHAVE_UNISTD_H=1', '-DVERSION="1.4"', '-D_GNU_SOURCE=1', '-DGIT_COMMIT="bfe0178"', '../src/common/ipc.c', '-c', '-o', '/Users/tehn/Work/lib/serialosc/build/src/common/ipc.c.2.o']

**Comment by nightmorph** [comment]
this looks like a duplicate of bug #28. same build error:

https://github.com/monome/serialosc/issues/28

**Comment by tehn** [comment]
duplicate, thanks for spotting.
