### ISSUE TITLE
macOS package doesn't install a binary in PATH

### ISSUE THREAD

**Issue by lazzarello** [monome/serialosc#44]
pkg installer from [4fec6f1](https://github.com/monome/serialosc/releases)

```
[lazzarello@macbookpro2 ~]$ which serialoscd
[lazzarello@macbookpro2 ~]$ 
```

macOS 10.12.6 (16G1212)

**Comment by artfwo** [comment]
hey! yeah, it does so by design. the executable is installed into `/Library/Application Support/Monome` and it is supposed to be launched automatically by `launchd`.

**Comment by lazzarello** [comment]
cool thanks, confirmed!

```
$ launchctl list | grep serial
438	0	org.monome.serialosc
```

 Currently can't get Max7 to connect to the grid. Moving to #45
