### ISSUE TITLE
serialosc package does not detect grid 128

### ISSUE THREAD

**Issue by lazzarello** [monome/serialosc#45]
```
brew install serialosc
$ serialoscd -v
serialoscd 1.4.1 (4fec6f1)
$ serialoscd 

```

No output when I connect a monobright grid 128.

Installing Max7 package and launching meadophysics reports no grid is connected.

This grid functions on Arch Linux.

10.12.6 (16G1212)

**Comment by artfwo** [comment]
have you uninstalled serialosc pkg, if installed previously ( asking after looking at #44 )? do you have OEM FTDI driver installed?

**Comment by lazzarello** [comment]
serialosc is running via the package installer, through `launchd`

```
$ launchctl list | grep serial
438	0	org.monome.serialosc
```

Max7 does not detect any grids connected.

**Comment by artfwo** [comment]
@lazzarello on MacOS 10.12 things are known to work with the [OEM FTDI driver](http://www.ftdichip.com/Drivers/VCP.htm). do you have that installed?

**Comment by lazzarello** [comment]
I installed the [FTDI driver](http://www.ftdichip.com/Drivers/VCP/MacOSX/FTDIUSBSerialDriver_v2_4_2.dmg) for my hardware. Max continues to display zero monomes. I have restarted my computer twice. I see the following in the console

```
udpreceiver: binding to port 12006
udpreceiver: binding to port 12288
udpreceiver: binding to port 13297
```

I'm not familiar enough with debugging serial port problem on macOS to have any intuition at this point.

**Comment by lazzarello** [comment]
Is [this article relevant for FTDI](https://arstechnica.com/information-technology/2014/10/windows-update-drivers-bricking-usb-serial-chips-beloved-of-hardware-hackers/)? I'm curious why the same grid device works with drivers in a Linux kernel.

**Comment by artfwo** [comment]
Not really relevant. The linux drivers generally work better than mac ones indeed. Did you also disable the apple driver after installing OEM driver? E.g. by running `sudo kextunload –b com.apple.driver.AppleUSBFTDI` ?

**Comment by lazzarello** [comment]
Ah...I will upgrade. I've been looking for a reason to do so.

**Comment by lazzarello** [comment]
yea! it works on 10.13 High Sierra. Thanks for your patience!

```
$ sw_vers -productVersion
10.13.3
$ serialoscd 
serialosc [m128_439]: connected, server running on port 14643
```
