### ISSUE TITLE
crash [12/59] Compiling third-party/libuv/src/unix/fs.c

### ISSUE THREAD

**Issue by kaosbeat** [monome/serialosc#51]
compiling serialOSC is not working on Raspberry Pi
I succesfully compiled serialOSC on RPi before...
is this because of libuv changed or because the way how serialOSC interacts with libuv changed?

this is the ./waf -v output:

`~/serialosc $ ./waf -v
Waf: Entering directory `/home/patch/serialosc/build'
[12/59] Compiling third-party/libuv/src/unix/fs.c
10:45:35 runner ['/usr/bin/gcc', '-std=c99', '-Wall', '-Werror', '-fvisibility=hidden', '-g', '--std=gnu89', '-Wall', '-Wextra', '-Wno-unused-parameter', '-Wstrict-prototypes', '-fPIC', '-Wno-cast-align', '-Ithird-party/libuv/include', '-I../third-party/libuv/include', '-Ithird-party/libuv/src', '-I../third-party/libuv/src', '-DHAVE_WORKING_POLL=1', '-DHAVE_LIBUDEV=1', '-DHAVE_LIBMONOME=1', '-DHAVE_LO=1', '-DHAVE_STRDUP=1', '-DHAVE_STRNDUP=1', '-DHAVE_STRCASECMP=1', '-DHAVE_UNISTD_H=1', '-DHAVE_DNS_SD_H=1', '-DVERSION="1.4.1a"', '-D_GNU_SOURCE=1', '-DGIT_COMMIT="51dbdc4"', '-D_GNU_SOURCE', '-D_POSIX_C_SOURCE=200112', '../third-party/libuv/src/unix/fs.c', '-c', '-o/home/patch/serialosc/build/third-party/libuv/src/unix/fs.c.1.o']
../third-party/libuv/src/unix/fs.c: In function 'uv__fs_copyfile':
../third-party/libuv/src/unix/fs.c:1154:20: error: comparison of integer expressions of different signedness: '__fsword_t' {aka 'int'} and 'unsigned int' [-Werror=sign-compare]
       if (s.f_type != /* CIFS */ 0xFF534D42u)
                    ^~
cc1: all warnings being treated as errors

Waf: Leaving directory `/home/patch/serialosc/build'
Build failed
 -> task in 'LIBUV' failed with exit status 1:
	{task 1983402992: c fs.c -> fs.c.1.o}
['/usr/bin/gcc', '-std=c99', '-Wall', '-Werror', '-fvisibility=hidden', '-g', '--std=gnu89', '-Wall', '-Wextra', '-Wno-unused-parameter', '-Wstrict-prototypes', '-fPIC', '-Wno-cast-align', '-Ithird-party/libuv/include', '-I../third-party/libuv/include', '-Ithird-party/libuv/src', '-I../third-party/libuv/src', '-DHAVE_WORKING_POLL=1', '-DHAVE_LIBUDEV=1', '-DHAVE_LIBMONOME=1', '-DHAVE_LO=1', '-DHAVE_STRDUP=1', '-DHAVE_STRNDUP=1', '-DHAVE_STRCASECMP=1', '-DHAVE_UNISTD_H=1', '-DHAVE_DNS_SD_H=1', '-DVERSION="1.4.1a"', '-D_GNU_SOURCE=1', '-DGIT_COMMIT="51dbdc4"', '-D_GNU_SOURCE', '-D_POSIX_C_SOURCE=200112', '../third-party/libuv/src/unix/fs.c', '-c', '-o/home/patch/serialosc/build/third-party/libuv/src/unix/fs.c.1.o']`

**Comment by artfwo** [comment]
right, the current version of libuv bundled with serialosc fails to build on armhf and it looks like [there is no fix yet](https://github.com/libuv/libuv/blob/v1.x/src/unix/fs.c#L1181).

a workaround might be to change the mentioned value to 0xFF534D42, but i haven't tried this myself.

**Comment by kaosbeat** [comment]
To what would I have to change it? I haven't got a clue...but I can try and
report back

**Comment by artfwo** [comment]
to `0xFF534D42` without the trailing `u`. or just run the configure stage as follows:

`CFLAGS=-Wno-error=sign-compare ./waf configure`

**Comment by kaosbeat** [comment]
I tried the CFLAGS option, it compiled fine!


thanks!
