### ISSUE TITLE
Segmentation fault on RPI Zero W - Raspberry Pi OS 20-08-20 

### ISSUE THREAD

**Issue by nordseele** [monome/serialosc#53]
### Environment : 
Device: Raspberry PI Zero W (Armv6) 
OS: Raspberry Pi OS 20-08-20 (same errors with the previous OS).

I tried to install Serialosc on a RPI Zero W following the instructions found on this page https://monome.org/docs/serialosc/raspbian/

Installing with the package fails so I tried to compile from source. Here are the details. 

### Install with the package:
 
- The service doesn't seem to start automatically. 
```
systemctl status serialosc.service
   serialosc.service
   Loaded: loaded (/lib/systemd/system/serialosc.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
```

- Running `serialoscd` manually returns a **_"Segmentation fault"_**. 

### Compiling from source: 

Serialosc won't compile easily.
./waf returns a lot of warnings/errors. Here's the full output of ./waf -v

![fb8fb18e09497794481795e7107ab1575d5fe725_2_1162x1000](https://user-images.githubusercontent.com/47527859/91658739-2b10bf80-eacb-11ea-90ce-4ce54314a8b8.jpeg)

Changing line 257 of serialosc/wscript to
conf.env.append_unique("CFLAGS", ["-std=c99", "-Wall", "-Wno-error"])
Serialosc will compile but `serialoscd` is not found 

<img width="566" alt="Capture d’écran 2020-08-30 à 14 33 40" src="https://user-images.githubusercontent.com/47527859/91659090-cd31a700-eacd-11ea-96e8-802fa9701aa9.png">

But after a reboot running `serialoscd` is working this time...

<img width="573" alt="Capture d’écran 2020-08-30 à 14 36 32" src="https://user-images.githubusercontent.com/47527859/91659128-3a453c80-eace-11ea-8662-3e1ce409c890.png">

**Comment by DevOps-Arts** [comment]
hi guys i can run any linux app on raspberry pi zero contact with me on gmail : [cybersecurty922@gmail.com](mailto:cybersecurty922@gmail.com)
skype: live:rehmanazhar922

i created my custom raspberry pi zeo image of armel architecture armel can run all

all the raasp os are armhf thats why error : armv7

Pakistani Hacker: Pakistan zindabaad!

**Comment by artfwo** [comment]
@nordseele  i've updated the libuv subdmodule in v1.4.4, but it no longer uses gyp, so the current waf script to build gyp projects can no longer be used with it.

alternatively, you can use waf with system libuv (installing libuv1-dev on RPi should be sufficient) or use cmake to build serialosc with bundled libuv as described in the README.

i am going to close this issue for now, but please feel free to reopen if the problem persists.
