### ISSUE TITLE
/sys/rotation not affecting arc

### ISSUE THREAD

**Issue by daveriedstra** [monome/serialosc#55]
Sending `/sys/rotation 90` (or 180 or 270) to serialosc has no effect on my arc. Is it supposed to? The documentation [page](https://github.com/monome/docs/blob/gh-pages/serialosc/osc.md#sys) mentions rotating the "monome", which I think classically refers to grid, so it's unclear.

I know I can just shift the LED values & encoder indices myself, but I'd prefer to use the API method if it's available.

**Comment by artfwo** [comment]
that's right. /sys/rotation has no effect on the arc.
