### ISSUE TITLE
liblo version rot

### ISSUE THREAD

**Issue by catfact** [monome/serialosc#57]
presently, seems like an old version of `liblo` is required. at some point, the entire low-level API changed to define e.g. `lo_server` as pointer-to-pointer instead of pointer-to-struct and the project will not build with the new version.

(i dodn't yet figure out where this change took place except to note that liblo 0.31 - the latest - does not work, whereas liblo 0.23 does.)

so maybe liblo should be added to the dependencies in `third-party` and frozen?

**Comment by artfwo** [comment]
it would be a minor problem later, when the base image is updated. i'd suggest adding the latest version of liblo in the norns repo and updating matron code instead, wdyt?

**Comment by artfwo** [comment]
sorry, hasn't woke up yet. :)

**Comment by artfwo** [comment]
serialosc builds fine with liblo-0.31 for me, what kind of build problems specifically did you experience?

**Comment by catfact** [comment]
apologies! i can't reproduce it now. must have been PEBKAC or a consequence of some other problem.
