### ISSUE TITLE
SerialOSC 1.4.3 on windows not compatible with monome 64 walnut edition

### ISSUE THREAD

**Issue by 256k** [monome/serialosc#60]
after some time trying to connect my monome 64 walnut edition to my windows PC using the latest serialOSC release from github with no success (either zero communication or the communication was messed up, I uninstalled it and installed the previous version 1.4.2-pre and it worked flawlessly.

tested using maxMSP 8 running grid-test.maxpat from the monome package with serial monitor.

a screenshot of the serial monitor is included
![serialmonitor](https://user-images.githubusercontent.com/16099871/145089310-091a7ecd-55f2-47d7-992f-f7efcdeb26f9.png)

**Comment by tehn** [comment]
thanks for the report. which version of windows are you running?

**Comment by aidanreilly** [comment]
Also seeing this issue with a grayscale 64. Works fine with version 1.4.2-pre

```
OS Name	Microsoft Windows 10 Pro
Version	10.0.19043 Build 19043
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Manufacturer	LENOVO
System Model	2325FG0
System Type	x64-based PC
System SKU	LENOVO_MT_2325
Processor	Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz, 2601 Mhz, 2 Core(s), 4 Logical Processor(s)
BIOS Version/Date	LENOVO G2ETB7WW (2.77 ), 24/09/2019
BIOS Mode	Legacy
```

**Comment by el-quinto** [comment]
The installation folder for serialosc 1.4.3 (C:\Program Files\Monome\serialosc) only contains protocol_mext.dll. The files protocol_40h.dll and protocol_series.dll that were included with earlier versions are missing, so it seems likely that all monobright editions are affected by this.

**Comment by artfwo** [comment]
@el-quinto good catch, i must have forgotten to include the other protocols when creating the 1.4.3 installer.

@aidanreilly @256k please check [v1.4.4](https://github.com/monome/serialosc/releases/tag/v1.4.4) build and reopen the issue if it issue persists for you.
