### ISSUE TITLE
prefix + device name pattern cleanup?

### ISSUE THREAD

**Issue by dndrks** [monome/serialosc#67]
chatting with Rylee + @tehn over the past few days, there seems to be an opportunity to streamline/clarify naming in the protocol.

the [current protocol doc](https://monome.org/docs/serialosc/serial.txt) lists these naming schemes:
**grid** `/prefix/led/set x y s`
**arc** `/prefix/ring/set n x a`

1. the grid naming scheme is documented incorrectly -- eg. the above pattern entry should be `/prefix/grid/led/set x y s`. I can correct this in the docs, but the note is helpful for the rest of this ticket.
2. @tehn's gut reaction was that arc follow suit with `/prefix/arc/ring/set n x a`. since arc is confidently out of production, i'm curious (@artfwo, tagging for your clear + brilliant head!) if this feels like it'd be a useful change or really just more annoying to touch up in any existent arc scripts?
3. if we _do_ opt to inject `arc` into the arc pattern, is there any usefulness to tightening up the relationship between the grid and arc patterns? eg.
    ```js
    /prefix/grid/led/level/set x y l // current form
    /prefix/arc/led/level/set n x l // proposed adjustment of /ring/set n x l
    ```

was originally going to open this as a discussion, but since there is *some* work to do, it makes sense to let it live as a ticket as we define it :)

**Comment by tehn** [comment]
thinking it over, feeling we should just keep it as is--- but fix the docs to reflect reality. @dndrks 

thanks for weighing in!
