### ISSUE TITLE
grid/key messages getting stuck (windows 10)

### ISSUE THREAD

**Issue by el-quinto** [monome/serialosc#68]
When there is a lot of LED activity, the grid/key messages don't seem to be getting through properly, with the grid/key off messages sometimes not coming through until the next grid/key on is triggered. Explained here - [https://llllllll.co/t/stuck-keys-issue-serialosc-windows-10/63208](url)

The issue is present with serialosc 1.4.2-pre and 1.4.3 on Windows 10. (serialosc 1.4 does not have this issue). I was unable to reproduce the issue on Mac OSX.

**Comment by artfwo** [comment]
@el-quinto thanks for reporting. this should now be fixed in https://github.com/monome/serialosc/releases/tag/v1.4.4
