### ISSUE TITLE
Windows bootloop issue

### ISSUE THREAD

**Issue by dessertplanet** [monome/serialosc#72]
Thread here: https://llllllll.co/t/serialosc-and-old-monomes-finaly-died-for-windows-with-last-update/66967

Posted by Lines user https://llllllll.co/u/luna_nane

They claim that serialosc is causing Windows devices with the latest updates to go into a bootloop of death.

If this reproduces and you do not already have somebody from MSFT to help out, let me know! (I work there)

**Comment by tehn** [comment]
Cannot reproduce.
